<?php

use Illuminate\Database\Seeder;

class PlacesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('places')->insert([
            ['user_id' => '1',
            'name' => '京都駅',
            'overview' => '電車に乗れる駅',
            'placetype_id' => '1',
            'attention_id' => '3',
            'pref' => '京都府',
            'address' => '京都市下京区東塩小路釜殿町',
            'phone' => '0570002486',
            'category_id' => '4',
            'url' => 'https://ja.kyoto.travel/tourism/single02.php?category_id=8&tourism_id=707',
            'status' => '1',
            ],
            ['user_id' => '1',
            'name' => '瑠璃光院',
            'overview' => '紅葉がとてもきれい',
            'placetype_id' => '2',
            'attention_id' => '1',
            'pref' => '京都府',
            'address' => '京都市左京区上高野東山606',
            'phone' => '0757814001',
            'category_id' => '4',
            'url' => 'http://rurikoin.komyoji.com/lp/',
            'status' => '1',
            ],
            ['user_id' => '1',
            'name' => '辻利兵衛本店',
            'overview' => '江戸時代に初代、辻利兵衛が衰退する宇治の茶園をみて「こんなに素晴らしいものを失くしたくない」と、17歳で茶園を買取り立志伝中の想いで起業してから156年、宇治茶の茶筋にこだわる老舗が、満を持して茶寮をオープン。着工から完成まで約3年を費やしたという茶寮は、製茶工場だった建物を一部改装して誕生させた老舗ならではの空間。歴史を感じる店内には、中庭を眺めながらお茶を味わえる特等席の「花見席」やソファーが並ぶ「喫茶スペース」がある。さらに、宇治抹茶が飲めるのはもちろん、パフェやわらび餅、ロールケーキなど素材にこだわりぬいたスイーツも揃っている。',
            'placetype_id' => '1',
            'attention_id' => '1',
            'pref' => '京都府',
            'address' => '',
            'phone' => '05053045484',
            'category_id' => '1',
            'url' => 'http://www.rakuten.ne.jp/gold/tsujirihei/',
            'status' => '1',
            ],
            ['user_id' => '1',
            'name' => '平安神宮',
            'overview' => '境内参拝時間　　6:00～17:00　※お守･お札･朱印は7:30～
            　　神苑拝観受付時間　　8:30～16:30',
            'placetype_id' => '2',
            'attention_id' => '2',
            'pref' => '京都府',
            'address' => '京都市左京区岡崎西天王町97',
            'phone' => '0757610221',
            'category_id' => '4',
            'url' => 'http://www.heianjingu.or.jp/',
            'status' => '1',
            ],
            ['user_id' => '1',
            'name' => 'いまいちなところ',
            'overview' => 'ここはあまり好きじゃない',
            'placetype_id' => '3',
            'attention_id' => '5',
            'pref' => '京都府',
            'address' => '',
            'phone' => '',
            'category_id' => '3',
            'url' => '',
            'status' => '1',
            ],
            ['user_id' => '1',
            'name' => '路地裏3坪雑貨店',
            'overview' => '見つけるとふらっと入ってしまうような魅力的なハンドメイドショップ。女の子なら誰しもワクワクして興奮するような可愛いアクセサリーがたくさん。行くたびに売られている商品が違ったりするので、気に入った商品があれば迷わずゲットしちゃう。ネット販売もしているのでぜひチェックしたい。',
            'placetype_id' => '1',
            'attention_id' => '1',
            'pref' => '京都府',
            'address' => '京都市東山区常盤町470-4',
            'phone' => '',
            'category_id' => '3',
            'url' => 'https://cupapa2007jp.wixsite.com/rojiura3',
            'status' => '1',
            ],
            ['user_id' => '1',
            'name' => 'ダイビング',
            'overview' => '透明感のある海でダイビングがしたい',
            'placetype_id' => '2',
            'attention_id' => '1',
            'pref' => '',
            'address' => '',
            'phone' => '',
            'category_id' => '4',
            'url' => '',
            'status' => '1',
            ],
            ['user_id' => '1',
            'name' => '白良浜',
            'overview' => 'ダイビングスポットでもあり、白い砂浜がとてもきれい・地元の人もみんな優しい素敵なところ',
            'placetype_id' => '1',
            'attention_id' => '1',
            'pref' => '',
            'address' => '',
            'phone' => '',
            'category_id' => '4',
            'url' => '',
            'status' => '1',
            ],
            ['user_id' => '1',
            'name' => '野田コスモス畑',
            'overview' => '秋にガチャに乗って降りた後田園風景を見ながら進んでいくと、広大なコスモス畑が見えてくる。周りが開けているのでどこで写真を撮ってもコスモスだらけでとてもきれい。電車の本数が少ないので帰る電車の時間もしっかり調べた方がいい。',
            'placetype_id' => '1',
            'attention_id' => '1',
            'pref' => '滋賀県',
            'address' => '近江八幡市野田町',
            'phone' => '',
            'category_id' => '4',
            'url' => '',
            'status' => '1',
            ],
        ]);
    }
}
